---

- name: Install LAMP stack
  hosts: all
  become: true

  tasks:

    - name: Set hostname if hostname is localhost
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/set_hostname.yml"
      when: ansible_hostname  == "localhost"

    - name: Install LAMP on Debian
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/lamp_debian.yml"
      when: ansible_os_family == "Debian"

    - name: Install LAMP on RHEL
      ansible.builtin.include_tasks: "{{ playbook_dir}}/tasks/lamp_rhel.yml"
      when: ansible_os_family == "RedHat"

    - name: Install LAMP on others
      ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/lamp_general.yml"
      when: ansible_os_family not in ['RedHat', 'Debian']

    - name: Create index page
      ansible.builtin.copy:
        dest: /var/www/html/index.php
        content: |
          <html>
          <head><title> LAMP stack in ON </title></head>
          <body><h1>Hello from "{{ ansible_hostname }}" page!</h1></body>
          </html>
        mode: '0644'

    - name: Remove default index file to not prioritize over index.php
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/www/html/index.html
        - /var/www/html/index.htm
