---

- name: ROLLBACK - Remove LAMP stack
  hosts: webservers
  become: true

  tasks:

    - name: Remove LAMP on Debian
      ansible.builtin.include_tasks: tasks/ROLLBACK_lamp_debian.yml
      when: ansible_os_family == "Debian"

    - name: Remove LAMP on RHEL
      ansible.builtin.include_tasks: tasks/ROLLBACK_lamp_rhel.yml
      when: ansible_os_family == "RedHat"

    - name: Remove index page
      ansible.builtin.file:
        path: /var/www/html/index.php
        state: absent

    - name: Replace the /etc/firewalld.conf  with the original one
      ansible.builtin.copy:
        src: files/rollback_files/etc_firewalld_conf_{{ inventory_hostname }}.bkp
        dest: /etc/firewalld/firewalld.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: restarted

    - name: Delete the backup files
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: "files/rollback_files/etc_firewalld_conf_{{ inventory_hostname }}.bkp"
        state: absent

    - name: Delete folder rollback_files in case its empty
      ansible.builtin.include_tasks: tasks/remove_empty_rollback_folder.yml


          #  handlers:
          #    - ansible.builtin.import_tasks: handlers/ROLLBACK_lamp_rhel.yml
          #    - ansible.builtin.import_tasks: handlers/ROLLBACK_lamp_debian.yml

