- name: ROLLBACK Deploy SSH Keys
  hosts: all
  become: true

  tasks:

  - name: Load CSV file with users
    ansible.builtin.include_tasks: tasks/load_csv.yml

  - name: Remove users
    ansible.builtin.user:
      name: "{{ item.User }}"
      state: absent
      remove: yes
    loop: "{{ all_users.list }}"

  - name: Remove user keys from local folder
    ansible.builtin.file:
      path: ./files/usr_keys
      state: absent
    delegate_to: localhost
    become: false
    run_once: true

  - name: Detect ssh demon
    ansible.builtin.set_fact:
      ssh_demon_name: "{{ 'ssh' if ansible_facts['distribution'] in ['Debian', 'Linux Mint'] else 'sshd' }}"

  - name: Replace the /etc/ssh/sshd_config  with the original one
    ansible.builtin.copy:
      src: files/rollback_files/etc_ssh_sshd_config_{{ inventory_hostname }}.bkp
      dest: /etc/ssh/sshd_config
      owner: root
      group: root
      mode: '0644'
    notify: Restart sshd

  - name: Delete the backup files for played hosts
    delegate_to: localhost
    become: false
    ansible.builtin.file:
      path: "files/rollback_files/etc_ssh_sshd_config_{{ inventory_hostname }}.bkp"
      state: absent
    loop: "{{ ansible_play_batch }}"

  - name: Delete folder rollback_files in case its empty
    ansible.builtin.include_tasks: tasks/remove_empty_rollback_folder.yml

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: "{{ ssh_demon_name }}"
        state: restarted
