---

- name: Update cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install full LAMP stack
  ansible.builtin.dnf:
    name:
      - httpd
      - mariadb-server
      - php
      - php-mysqlnd

- name: Start Apache demon
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Start MariaDB demon
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
    
