---

- name: Register folder content
  delegate_to: localhost
  become: false
  ansible.builtin.find:
    path: "{{ playbook_dir }}/files/rollback_files"
    file_type: file
  register: rollback_folder_content

- name: Delete folder rollback_files
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ playbook_dir }}/files/rollback_files"
    state: absent
  when: rollback_folder_content.matched == 0
