---

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Install full LAMP stack
  ansible.builtin.apt:
    name:
      - apache2
      - mariadb-server
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Start Apache demon
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Start mariaDB demon
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
