---

- name: Update cache
  ansible.builtin.apt:
    update_cache: true

- name: Remove full LAMP stack
  ansible.builtin.apt:
    name:
      - apache2
      - mariadb-server
      - php
      - libapache2-mod-php
      - php-mysql
    state: absent
    purge: true

- name: Get the facts about services
  ansible.builtin.service_facts:

- name: Stop Debian Apache
  ansible.builtin.service:
    name: apache2
    state: stopped
    enabled: false
  when: "'apache2.service' in services"

- name: Stop Debian mariaDB
  ansible.builtin.service:
    name: mariadb
    state: stopped
    enabled: false
  when: "'mariadb.service' in services"

