---

- name: Load CSV file
  ansible.builtin.include_tasks: ../tasks/load_csv.yml

- name: Create users
  ansible.builtin.user:
    name: "{{ item.User  }}"
    shell: /bin/bash
    create_home: true
    comment: "{{ item.Comment }} -team {{ item['Owner-Team'] }}"
    state: present
  loop: "{{ all_users.list }}"

- name: Deploy existing RSA keys for users
  ansible.posix.authorized_key:
    user: "{{ item.User }}"
    key: "{{ item['Pub-key'] | trim }}"
    state: present
  loop: "{{ all_users.list }}"
  when: item['Pub-key'] is defined and (item['Pub-key'] | trim) !=''

- name: Create a local folder for storing keys for functional users
  ansible.builtin.file:
    path: "./files/usr_keys/"
    state: directory
  delegate_to: localhost
  become: false

- name: Generate keys for functional users
  community.crypto.openssh_keypair:
    path: "./files/usr_keys/id_{{ item.User }}"
    type: ed25519
    comment: "{{ item.User }}"
    force: false
  loop: "{{ all_users.list }}"
  when: item.Functional == '1'
  delegate_to: localhost
  become: false

- name: Create ssh folder for functional users
  ansible.builtin.file:
    path: "/home/{{ item.User }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ item.User }}"
    group: "{{ item.User }}"
  loop: "{{ all_users.list }}"
